# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  profile: chill
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!.cache/**"
    - "!result/**"
    - "!flake.lock"
  tools:
    clippy:
      enabled: true
    actionlint:
      enabled: true
    shellcheck:
      enabled: true
    gitleaks:
      enabled: true
    markdownlint:
      enabled: true
    languagetool:
      enabled: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  code_guidelines:
    enabled: true
    filePatterns:
      - "CLAUDE.md"
