name: Branch Restrictions

on:
  pull_request:
    branches:
      - main

env:
  ALLOWED_PATTERN: "^(develop|hotfix/.+)$"

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Checking branch: $HEAD_REF"
          echo "Allowed pattern: $ALLOWED_PATTERN"

          if [[ "$HEAD_REF" =~ $ALLOWED_PATTERN ]]; then
            echo "Branch '$HEAD_REF' is allowed to merge to main"
          else
            echo "Error: Branch '$HEAD_REF' does not match allowed pattern: $ALLOWED_PATTERN"
            exit 1
          fi
